#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Nginx 配置生成模块
用于生成 Nginx SSL 证书配置文件
"""

import logging
import os
from datetime import datetime, timezone
from typing import Dict, Optional

logger = logging.getLogger(__name__)


class NginxConfigGenerator:
    """Nginx 配置生成器"""

    def __init__(self, config_manager):
        """初始化 Nginx 配置生成器
        
        Args:
            config_manager: 配置管理器实例
        """
        self.config_manager = config_manager
        self.template_path = self._get_template_path()

    def _get_template_path(self) -> str:
        """获取模板文件路径"""
        # 模板文件位于 config 目录下
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        return os.path.join(project_root, 'config', 'nginx-ssl.conf.template')

    def _load_template(self) -> str:
        """加载模板文件内容
        
        Returns:
            模板文件内容
        """
        try:
            with open(self.template_path, 'r', encoding='utf-8') as f:
                return f.read()
        except FileNotFoundError:
            logger.error(f"Nginx 配置模板文件未找到: {self.template_path}")
            # 返回默认模板
            return self._get_default_template()
        except Exception as e:
            logger.error(f"读取 Nginx 配置模板失败: {e}")
            return self._get_default_template()

    def _get_default_template(self) -> str:
        """获取默认模板内容"""
        return """# Nginx SSL Certificate Configuration Template
# This file is automatically generated by cert-manager
# Domain: {domain}
# Generated at: {generated_at}

ssl_certificate {cert_directory}/fullchain.pem;
ssl_certificate_key {cert_directory}/privkey.pem;
ssl_trusted_certificate {cert_directory}/fullchain.pem;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1h;
ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;"""

    def generate_config(self, domain: str, cert_directory: str,
                        custom_template: Optional[str] = None) -> str:
        """生成 Nginx 配置内容
        
        Args:
            domain: 域名
            cert_directory: 证书目录
            custom_template: 自定义模板内容（可选）
            
        Returns:
            生成的配置内容
        """
        # 使用自定义模板或加载默认模板
        template = custom_template or self._load_template()

        # 替换模板变量
        config_content = template.replace('{domain}', domain)
        config_content = config_content.replace('{cert_directory}', cert_directory)
        config_content = config_content.replace('{generated_at}',
                                                datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S'))

        return config_content

    def get_cert_directory(self, domain: str, server_config: Dict) -> str:
        """获取证书目录

        Args:
            domain: 域名
            server_config: 服务器配置

        Returns:
            证书目录
        """
        return server_config.get('cert_directory', '/etc/nginx/certs/{domain}').replace('{domain}', domain)

    def get_config_file_path(self, domain: str, server_config: Dict) -> Optional[str]:
        """获取配置文件路径
        
        Args:
            domain: 域名
            server_config: 服务器配置
            
        Returns:
            配置文件路径，如果未配置则返回 None
        """

        cert_conf_file = server_config.get(
            'cert_conf_file',
            os.path.join(self.get_cert_directory(domain, server_config), 'cert.conf')
        )

        # 替换域名变量
        config_path = cert_conf_file.replace('{domain}', domain)
        return config_path

    def generate_config_file_content(self, domain: str, server_config: Dict) -> Optional[str]:
        """为指定服务器生成配置文件内容
        
        Args:
            domain: 域名
            server_config: 服务器配置
            
        Returns:
            配置文件内容，如果不需要生成则返回 None
        """
        return self.generate_config(domain, self.get_cert_directory(domain, server_config))
